//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Meow.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MeowParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IMeowVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] MeowParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat([NotNull] MeowParser.StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] MeowParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.typeid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeid([NotNull] MeowParser.TypeidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] MeowParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecl([NotNull] MeowParser.DeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.declhead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclhead([NotNull] MeowParser.DeclheadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] MeowParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.assignhead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignhead([NotNull] MeowParser.AssignheadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.crement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrement([NotNull] MeowParser.CrementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.callstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallstmt([NotNull] MeowParser.CallstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] MeowParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] MeowParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.ifelse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfelse([NotNull] MeowParser.IfelseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.whilelp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhilelp([NotNull] MeowParser.WhilelpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.forlp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForlp([NotNull] MeowParser.ForlpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] MeowParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] MeowParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp([NotNull] MeowParser.CompContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] MeowParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] MeowParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.expo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpo([NotNull] MeowParser.ExpoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.unop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnop([NotNull] MeowParser.UnopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnit([NotNull] MeowParser.UnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] MeowParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MeowParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] MeowParser.VariableContext context);
}
