namespace symnames {
    enum SymType {  TOK_VOID, TOK_INT, TOK_STRING, TOK_FLOAT,
                    TOK_IF, TOK_ELSE, TOK_WHILE, TOK_FOR, TOK_UNTIL, TOK_RETURN, TOK_STRUCT,
                    TOK_NULLPTR, TOK_ARRAY, TOK_ARROW, TOK_ALLOC, TOK_PTR,
                    TOK_EQ, TOK_NE, TOK_LT, TOK_LE, TOK_GT, TOK_GE, TOK_NOT,
                    TOK_ADDEQ, TOK_SUBEQ, TOK_INC, TOK_DEC,
                    TOK_IDENT, TOK_INTCON, TOK_CHARCON, TOK_STRINGCON, TOK_FLOATCON,
                    TOK_ROOT, TOK_BLOCK, TOK_CALL, TOK_FUNCTION, TOK_PARAM, TOK_TYPE_ID,
                    TOK_INT2FLOAT, TOK_FLOAT2INT, TOK_INT2STRING, TOK_FLOAT2STRING, TOK_MOMMY, BITSET_SIZE
                 };

    
}