//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\dinop\Documents\UCSC\meow\rewrite\java\Meow.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMeowListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MeowBaseListener : IMeowListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] MeowParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] MeowParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] MeowParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] MeowParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] MeowParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] MeowParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.typeid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeid([NotNull] MeowParser.TypeidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.typeid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeid([NotNull] MeowParser.TypeidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] MeowParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] MeowParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecl([NotNull] MeowParser.DeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecl([NotNull] MeowParser.DeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.declhead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclhead([NotNull] MeowParser.DeclheadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.declhead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclhead([NotNull] MeowParser.DeclheadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] MeowParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] MeowParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.assignhead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignhead([NotNull] MeowParser.AssignheadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.assignhead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignhead([NotNull] MeowParser.AssignheadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.crement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCrement([NotNull] MeowParser.CrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.crement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCrement([NotNull] MeowParser.CrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.callstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallstmt([NotNull] MeowParser.CallstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.callstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallstmt([NotNull] MeowParser.CallstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] MeowParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] MeowParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] MeowParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] MeowParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.ifelse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfelse([NotNull] MeowParser.IfelseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.ifelse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfelse([NotNull] MeowParser.IfelseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.whilelp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilelp([NotNull] MeowParser.WhilelpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.whilelp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilelp([NotNull] MeowParser.WhilelpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.forlp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForlp([NotNull] MeowParser.ForlpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.forlp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForlp([NotNull] MeowParser.ForlpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn([NotNull] MeowParser.ReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn([NotNull] MeowParser.ReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] MeowParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] MeowParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp([NotNull] MeowParser.CompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp([NotNull] MeowParser.CompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] MeowParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] MeowParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] MeowParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] MeowParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.expo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpo([NotNull] MeowParser.ExpoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.expo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpo([NotNull] MeowParser.ExpoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.unop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnop([NotNull] MeowParser.UnopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.unop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnop([NotNull] MeowParser.UnopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnit([NotNull] MeowParser.UnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnit([NotNull] MeowParser.UnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] MeowParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] MeowParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] MeowParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] MeowParser.VariableContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
